axis_linear: 1  # Left thumb stick vertical
scale_linear: 0.5
scale_linear_turbo: 2.4

axis_angular: 0  # Left thumb stick horizontal
scale_angular: 0.5

enable_button: 7  # ZR
enable_turbo_button: 5  # R
